Feature/product tile
gilwong00/derp-cart pull request #18
Opened 2021-04-07 07:26 UTC by jess-lam

2021-04-07 21:18 UTC, gilwong00 requested changes
@jess-lam we should make the product tile its own component. can you make a new .tsx file and a scss file for the product tile inside the product folder

2021-04-07 21:18 UTC, gilwong00 commented on src/components/Product/ProductGrid.tsx
> +            <div className={styles.product_tile} key={product.id}>
this should be its own component

2021-04-08 01:27 UTC, jess-lam commented on src/components/Product/ProductGrid.tsx
> +            <div className={styles.product_tile} key={product.id}>
Ok. I just extracted it out.

2021-04-08 03:13 UTC, gilwong00 requested changes

2021-04-08 03:13 UTC, gilwong00 commented on src/components/Product/ProductGrid.module.scss
> +  // .product_tile {
can we remove these comments if they are no longer needed

2021-04-08 03:13 UTC, gilwong00 commented on src/components/Product/ProductGrid.tsx
> +            <ProductTile product={product} />
need a key here

2021-04-08 03:13 UTC, gilwong00 commented on src/components/ProductTile/ProductTile.tsx
> +      <img className= {styles.heart} src="/heart.png"/>
i dont think we need this heart icon atm. lets comment it out

2021-04-08 03:15 UTC, gilwong00 commented
<img width="395" alt="Screen Shot 2021-04-07 at 8 11 53 PM" src="https://user-images.githubusercontent.com/17975035/113963075-cabeca80-97dd-11eb-9fa2-74b23fea50cb.png">

@jess-lam couple of changes here
- lets up the font size to 16px for the title
- im not loving where the price is can we display it on the same line as the add to bag button, @courtniwong what do you think?
- lets rename add to bag to add to cart

2021-05-19 05:51 UTC, merged